---
version: "3.9"
services:
  fullnode:
    image: mysten/sui-node:${SUI_IMAGE_GIT_BRANCH_OR_COMMIT_HASH}
    ports:
      - "8080:8080/udp"
      - "9000:9000"
      - "9184:9184"
    volumes:
      - ./fullnode.yaml:/sui/fullnode.yaml:ro
      - ./genesis.blob:/sui/genesis.blob:ro
      - ${SUI_HOME_DIRECTORY}/suidb:/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
volumes:
  suidb: